version: '3.2'

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "PostgresAdmin"
    ports:
      - "11432:5432"
    volumes:
      - ./volume/pgdata:/var/lib/postgresql/data 
    networks:
      - pgnet
      
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "11543:80"
    depends_on:
      - db
    networks:
      - pgnet

networks: 
  pgnet:
    driver: bridge
